### ISSUE TITLE
Error when using package glossaries

### ISSUE THREAD

**Issue by leluque** [lfochamon/poliTeX#1] opened 2015-10-01 13:57 UTC
I'm trying to use the package 'glossaries' together with the poliTeX class to generate an acronym list, but when I do that, I get the following error messages (see below). To replicate the error, only include \usepackage{glossaries} at the beginning of the TeX document.

! LaTeX Error: Command \su@ExpandTwoArgs already defined.
Or name \end... illegal, see p.192 of the manual.
See the LaTeX manual or LaTeX Companion for explanation.
Type H <return> for immediate help.
...
l.89 }
Your command was ignored.
Type I <command> <return> to replace it with another command,
or <return> to continue without it.
! LaTeX Error: Command \IfSubStringInString already defined.
Or name \end... illegal, see p.192 of the manual.
See the LaTeX manual or LaTeX Companion for explanation.
Type H <return> for immediate help.
...
l.94 }
Your command was ignored.
Type I <command> <return> to replace it with another command,
or <return> to continue without it.
! LaTeX Error: Command \su@IfSubStringInString already defined.
Or name \end... illegal, see p.192 of the manual.
See the LaTeX manual or LaTeX Companion for explanation.
Type H <return> for immediate help.
...

**Comment by lfochamon** [comment] 2015-10-02 18:18
OK... I couldn't reproduce this error. The tex compiles with the `glossaries` package and runs `makeindex` without issues (couldn't test `makeglossaries` because I don't have perl on this PC). Are you using `abntex2cite`? You may want to include `glossaries` before `abntex2cite` (which defines a lot of `substr` functions if they are not yet defined). That's is an abntex2 issue, but easily fixed by taking care of the package orders. Let me know if there's anything else!

Referring to your email, I have updated the class to include an `pretextualsection` environment that let's you add list of symbols, acronyms, and whatever else you want! Check out the new README.

(Ah... E esse pacote só tem uso para a POLI, então acho que não tem problema discutirmos em português aqui... Mas vocês que sabem!)

**Closed as completed** 2015-11-04 02:57 UTC
